 <style type="text/css">
 
      .navbar {
      color: red !important;
      height: 40px;
  }
.navbar-cls-top {
    background: none repeat scroll 0 0 red !important;
    border-bottom: medium none;
    margin-top:-4px !important; 
}
/*.btn-custom { background-color: hsl(70, 11%, 71%) !important; background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#eeefeb", endColorstr="#babdac"); background-image: -khtml-gradient(linear, left top, left bottom, from(#eeefeb), to(#babdac)); background-image: -moz-linear-gradient(top, #eeefeb, #babdac); background-image: -ms-linear-gradient(top, #eeefeb, #babdac); background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #eeefeb), color-stop(100%, #babdac)); background-image: -webkit-linear-gradient(top, #eeefeb, #babdac); background-image: -o-linear-gradient(top, #eeefeb, #babdac); background-image: linear-gradient(#eeefeb, #babdac); border-color: #babdac #babdac hsl(70, 11%, 65.5%); color: #333 !important; text-shadow: 0 1px 1px rgba(255, 255, 255, 0.36); -webkit-font-smoothing: antialiased; }*/
/*.btn-custom { background-color: hsl(0, 100%, 76%) !important; background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#feadad", endColorstr="#ff8484"); background-image: -khtml-gradient(linear, left top, left bottom, from(#feadad), to(#ff8484)); background-image: -moz-linear-gradient(top, #feadad, #ff8484); background-image: -ms-linear-gradient(top, #feadad, #ff8484); background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #feadad), color-stop(100%, #ff8484)); background-image: -webkit-linear-gradient(top, #feadad, #ff8484); background-image: -o-linear-gradient(top, #feadad, #ff8484); background-image: linear-gradient(#feadad, #ff8484); border-color: #ff8484 #ff8484 hsl(0, 100%, 74%); color: #333 !important; text-shadow: 0 1px 1px rgba(255, 255, 255, 0.13); -webkit-font-smoothing: antialiased; }*/
/*.btn-custom { background-color: hsl(193, 32%, 68%) !important; background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#f8fafb", endColorstr="#93bcc7"); background-image: -khtml-gradient(linear, left top, left bottom, from(#f8fafb), to(#93bcc7)); background-image: -moz-linear-gradient(top, #f8fafb, #93bcc7); background-image: -ms-linear-gradient(top, #f8fafb, #93bcc7); background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f8fafb), color-stop(100%, #93bcc7)); background-image: -webkit-linear-gradient(top, #f8fafb, #93bcc7); background-image: -o-linear-gradient(top, #f8fafb, #93bcc7); background-image: linear-gradient(#f8fafb, #93bcc7); border-color: #93bcc7 #93bcc7 hsl(193, 32%, 60.5%); color: #333 !important; text-shadow: 0 1px 1px rgba(255, 255, 255, 0.49); -webkit-font-smoothing: antialiased; }*/
/*.btn-custom { background-color: hsl(41, 85%, 74%) !important; background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#fefbf5", endColorstr="#f5d184"); background-image: -khtml-gradient(linear, left top, left bottom, from(#fefbf5), to(#f5d184)); background-image: -moz-linear-gradient(top, #fefbf5, #f5d184); background-image: -ms-linear-gradient(top, #fefbf5, #f5d184); background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fefbf5), color-stop(100%, #f5d184)); background-image: -webkit-linear-gradient(top, #fefbf5, #f5d184); background-image: -o-linear-gradient(top, #fefbf5, #f5d184); background-image: linear-gradient(#fefbf5, #f5d184); border-color: #f5d184 #f5d184 hsl(41, 85%, 68%); color: #333 !important; text-shadow: 0 1px 1px rgba(255, 255, 255, 0.39); -webkit-font-smoothing: antialiased; }*/
/*.btn-custom { background-color: hsl(195, 79%, 79%) !important; background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#fafdfe", endColorstr="#9fdef3"); background-image: -khtml-gradient(linear, left top, left bottom, from(#fafdfe), to(#9fdef3)); background-image: -moz-linear-gradient(top, #fafdfe, #9fdef3); background-image: -ms-linear-gradient(top, #fafdfe, #9fdef3); background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fafdfe), color-stop(100%, #9fdef3)); background-image: -webkit-linear-gradient(top, #fafdfe, #9fdef3); background-image: -o-linear-gradient(top, #fafdfe, #9fdef3); background-image: linear-gradient(#fafdfe, #9fdef3); border-color: #9fdef3 #9fdef3 hsl(195, 79%, 74%); color: #333 !important; text-shadow: 0 1px 1px rgba(255, 255, 255, 0.33); -webkit-font-smoothing: antialiased; }*/
.btn-custom { background-color: hsl(558, 60%, 72%) !important; border-bottom: 2px solid black !important; background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#b5deec", endColorstr="#8ccde2"); background-image: -khtml-gradient(linear, left top, left bottom, from(#b5deec), to(#8ccde2)); background-image: -moz-linear-gradient(top, #b5deec, #8ccde2); background-image: -ms-linear-gradient(top, #b5deec, #8ccde2); background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #b5deec), color-stop(100%, #8ccde2)); background-image: -webkit-linear-gradient(top, #b5deec, #8ccde2); background-image: -o-linear-gradient(top, #b5deec, #8ccde2); background-image: linear-gradient(#b5deec, #8ccde2); border-color: #8ccde2 #8ccde2 hsl(195, 60%, 69.5%); color: #333 !important; text-shadow: 0 1px 1px rgba(255, 255, 255, 0.16); -webkit-font-smoothing: antialiased; }
.btn-new { background-color: hsl(0, 0%, 16%) !important; background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#5b5b5b", endColorstr="#282828"); background-image: -khtml-gradient(linear, left top, left bottom, from(#5b5b5b), to(#282828)); background-image: -moz-linear-gradient(top, #5b5b5b, #282828); background-image: -ms-linear-gradient(top, #5b5b5b, #282828); background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #5b5b5b), color-stop(100%, #282828)); background-image: -webkit-linear-gradient(top, #5b5b5b, #282828); background-image: -o-linear-gradient(top, #5b5b5b, #282828); background-image: linear-gradient(#5b5b5b, #282828); border-color: #282828 #282828 hsl(0, 0%, 11%); color: #fff !important; text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.33); -webkit-font-smoothing: antialiased; }
 </style>

      

        
 <nav class="navbar navbar-default navbar-cls-top btn-custom " role="navigation" style="margin-bottom: -25px;">
            <div style="margin:6px 6px 6px 6px;">
            <a href="<?php echo site_url('admin');?>" class="btn btn-new btn-lg pull-right" style="margin:-14px 6px 6px 6px;" shape=""><span class="glyphicon glyphicon-off"></span> </a>
            <a id="dashboard" href="<?php echo site_url('admin/dashboard'); ?>" class="btn btn-new btn-md pull-left" style="margin:-10px 6px 6px -3px;" shape=""><span class="glyphicon glyphicon-th-list"></span> Dashboard </a>
            <h2 class="text-center" style="color:white;font-family:-moz-fixed">Welcome To Admin Panel</h2>
             </div>
        </nav> 

        
        